name: Build and Deploy to Zeabur

on:
  push:
    branches:
      - main  # 當你 push 到 main 分支時會觸發

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 18  # 你可以換成專案需要的 Node 版本

      - name: Install dependencies
        run: yarn install  # 或 npm install

      - name: Build project
        run: yarn build    # 或你實際的 build 指令，如 npx turbo run build --filter=web

      - name: Trigger Zeabur deployment
        env:
          ZEABUR_API_TOKEN: ${{ secrets.ZEABUR_API_TOKEN }}
          ZEABUR_PROJECT_ID: ${{ secrets.ZEABUR_PROJECT_ID }}
          ZEABUR_SERVICE_ID: ${{ secrets.ZEABUR_SERVICE_ID }}
        run: |
          curl -X POST "https://gateway.zeabur.com/api/deployments" \
            -H "Authorization: Bearer $ZEABUR_API_TOKEN" \
            -H "Content-Type: application/json" \
            -d "{\"projectId\":\"$ZEABUR_PROJECT_ID\",\"serviceId\":\"$ZEABUR_SERVICE_ID\"}"
