name: Build and Deploy Cal.com to Zeabur

on:
  push:
    branches:
      - main

env:
  NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
  DATABASE_URL: ${{ secrets.DATABASE_URL }}
  NEXT_PUBLIC_WEBAPP_URL: ${{ secrets.NEXT_PUBLIC_WEBAPP_URL }}
  NEXT_PUBLIC_WEBSITE_URL: ${{ secrets.NEXT_PUBLIC_WEBSITE_URL }}
  NEXT_PUBLIC_SINGLE_ORG_SLUG: booker
  NEXTAUTH_URL: ${{ secrets.NEXTAUTH_URL }}
  NODE_OPTIONS: --max_old_space_size=4096

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: |
            ~/.npm
            .turbo
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm install

      - name: Build Cal.com
        run: npx turbo run build --filter=web

      - name: Deploy to Zeabur
        run: curl -X POST ${{ secrets.ZEABUR_DEPLOY_HOOK_URL }}
