name: Build and Deploy to Zeabur

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: yarn install
        
      - name: Build All (Turbo)
        run: npx turbo run build --filter=web^...

      - name: Trigger Zeabur deployment
        env:
           NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
           DATABASE_URL: ${{ secrets.DATABASE_URL }}
           NEXTAUTH_URL: ${{ secrets.NEXTAUTH_URL }}
           NEXT_PUBLIC_WEBAPP_URL: ${{ secrets.NEXT_PUBLIC_WEBAPP_URL }}
           NEXT_PUBLIC_WEBSITE_URL: ${{ secrets.NEXT_PUBLIC_WEBSITE_URL }}
           ZEABUR_API_TOKEN: ${{ secrets.ZEABUR_API_TOKEN }}
           ZEABUR_PROJECT_ID: ${{ secrets.ZEABUR_PROJECT_ID }}
           ZEABUR_SERVICE_ID: ${{ secrets.ZEABUR_SERVICE_ID }}
        run: |
          curl -X POST "https://gateway.zeabur.com/api/deployments" \
            -H "Authorization: Bearer $ZEABUR_API_TOKEN" \
            -H "Content-Type: application/json" \
            -d "{\"projectId\":\"$ZEABUR_PROJECT_ID\",\"serviceId\":\"$ZEABUR_SERVICE_ID\"}"
